import { NodeConnectionTypes, type INodeType, type INodeTypeDescription } from 'n8n-workflow';

export class Scriberr implements INodeType {
	description: INodeTypeDescription = {
	 		displayName: 'Scriberr',
		name: 'scriberr',
			icon: { light: 'file:../../icons/scriberr.svg', dark: 'file:../../icons/scriberr.dark.svg' },
 		group: ['input'],
 		version: 1,
 		subtitle: '={{$parameter["operation"] + ": " + $parameter["resource"]}}',
 		description: 'Interact with the Scriberr API (transcriptions, notes, chat, summaries)',
 		defaults: { name: 'Scriberr' },
 		usableAsTool: true,
 		inputs: [NodeConnectionTypes.Main],
 		outputs: [NodeConnectionTypes.Main],
 		credentials: [
 			{
 				name: 'scriberrApiKeyApi',
 				required: true,
 				displayOptions: {
 					show: {
 						authentication: ['apiKey'],
 					},
 				},
 			},
 			{
 				name: 'scriberrJwtApi',
 				required: true,
 				displayOptions: {
 					show: {
 						authentication: ['jwt'],
 					},
 				},
 			},
 		],
 		requestDefaults: {
 			baseURL: '={{$credentials.baseUrl}}',
 			headers: {
 				Accept: 'application/json',
 				'Content-Type': 'application/json',
 			},
 		},
 		properties: [
 			{
 				displayName: 'Authentication',
 				name: 'authentication',
 				type: 'options',
 				options: [
 					{ name: 'API Key', value: 'apiKey' },
 					{ name: 'JWT (Bearer Token)', value: 'jwt' },
 				],
 				default: 'apiKey',
 			},

 			{
 				displayName: 'Resource',
 				name: 'resource',
 				type: 'options',
 				noDataExpression: true,
	 			options: [
	 				{ name: 'Admin', value: 'admin' },
	 				{ name: 'API Key', value: 'apiKey' },
	 				{ name: 'Auth', value: 'auth' },
	 				{ name: 'Chat', value: 'chat' },
	 				{ name: 'Health', value: 'health' },
	 				{ name: 'LLM', value: 'llm' },
	 				{ name: 'Note', value: 'note' },
	 				{ name: 'Profile', value: 'profile' },
	 				{ name: 'Summary', value: 'summary' },
	 				{ name: 'Transcription', value: 'transcription' },
	 			],
 				default: 'transcription',
 			},

 			// Transcription operations
 			{
 				displayName: 'Operation',
 				name: 'operation',
 				type: 'options',
 				noDataExpression: true,
 				displayOptions: { show: { resource: ['transcription'] } },
	 				options: [
	 					{
	 						name: 'Delete',
	 						value: 'delete',
	 						action: 'Delete transcription job',
	 						description: 'Delete a transcription job and its associated files',
							routing: { request: { method: 'DELETE', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}' } },
	 					},
	 					{
	 						name: 'Get',
	 						value: 'get',
	 						action: 'Get transcription',
	 						description: 'Get a transcription by ID',
								routing: { request: { method: 'GET', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}' } },
	 					},
	 					{
	 						name: 'Get Audio',
	 						value: 'getAudio',
	 						action: 'Get audio file',
	 						description: 'Serve the audio file for a transcription job',
							routing: { request: { method: 'GET', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}/audio' } },
	 					},
	 					{
	 						name: 'Get Models',
	 						value: 'getModels',
	 						action: 'Get supported models',
	 						description: 'Get list of supported WhisperX models',
							routing: { request: { method: 'GET', url: '/api/v1/transcription/models' } },
	 					},
	 					{
	 						name: 'Get Quick Transcription',
	 						value: 'getQuickTranscription',
	 						action: 'Get quick transcription status',
	 						description: 'Get the current status of a quick transcription job',
							routing: { request: { method: 'GET', url: '/api/v1/transcription/quick/{{$parameter["quickTranscriptionId"]}}' } },
	 					},
	 					{
	 						name: 'Get Status',
	 						value: 'getStatus',
	 						action: 'Get transcription status',
	 						description: 'Get the current status of a transcription job',
							routing: { request: { method: 'GET', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}/status' } },
	 					},
	 					{
	 						name: 'Get Summary',
	 						value: 'getSummary',
	 						action: 'Get latest summary',
	 						description: 'Get the most recent saved summary for the given transcription',
							routing: { request: { method: 'GET', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}/summary' } },
	 					},
	 					{
	 						name: 'Get Transcript',
	 						value: 'getTranscript',
	 						action: 'Get transcript',
	 						description: 'Get the transcript for a completed transcription job',
							routing: { request: { method: 'GET', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}/transcript' } },
	 					},
	 					{
	 						name: 'Kill Job',
	 						value: 'kill',
	 						action: 'Kill running transcription job',
	 						description: 'Cancel a currently running transcription job',
							routing: { request: { method: 'POST', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}/kill' } },
	 					},
	 					{
	 						name: 'List',
	 						value: 'list',
	 						action: 'List transcriptions',
	 						description: 'Get a list of all transcription records',
							routing: { request: { method: 'GET', url: '/api/v1/transcription/list' } },
	 					},
	 					{
	 						name: 'Quick Transcription',
	 						value: 'quickTranscription',
	 						action: 'Submit quick transcription job',
	 						description: 'Submit an audio file for temporary transcription (data discarded after 6 hours)',
							routing: { request: { method: 'POST', url: '/api/v1/transcription/quick' } },
	 					},
	 					{
	 						name: 'Start Transcription',
	 						value: 'startTranscription',
	 						action: 'Start transcription for uploaded file',
	 						description: 'Start transcription for an already uploaded audio file',
							routing: { request: { method: 'POST', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}/start' } },
	 					},
	 					{
	 						name: 'Submit',
	 						value: 'submit',
	 						action: 'Submit a transcription job',
	 						description: 'Submit an audio file for transcription with WhisperX',
							routing: { request: { method: 'POST', url: '/api/v1/transcription/submit' } },
	 					},
	 					{
	 						name: 'Update Title',
	 						value: 'updateTitle',
	 						action: 'Update transcription title',
	 						description: 'Update the title of an audio file / transcription',
							routing: { request: { method: 'PUT', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}/title' } },
	 					},
	 					{
	 						name: 'Upload',
	 						value: 'upload',
	 						action: 'Upload audio file',
	 						description: 'Upload an audio file without starting transcription',
							routing: { request: { method: 'POST', url: '/api/v1/transcription/upload' } },
	 					},
	 				],
 				default: 'list',
 			},
 			{
 				displayName: 'Transcription ID',
 				name: 'transcriptionId',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'ID of the transcription job',
 				displayOptions: { show: { resource: ['transcription'], operation: ['get','getStatus','getTranscript','getSummary','kill','updateTitle','delete','getAudio','startTranscription'] } },
 			},
 			{
 				displayName: 'Quick Transcription ID',
 				name: 'quickTranscriptionId',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'ID of the quick transcription job',
 				displayOptions: { show: { resource: ['transcription'], operation: ['getQuickTranscription'] } },
 			},
 			{
 				displayName: 'Audio File',
 				name: 'audioFile',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Path or field name containing the audio file for upload',
 				displayOptions: { show: { resource: ['transcription'], operation: ['submit', 'upload', 'quickTranscription'] } },
 			},
 			{
 				displayName: 'Job Title',
 				name: 'jobTitle',
 				type: 'string',
 				default: '',
 				description: 'Title for the transcription job',
 				displayOptions: { show: { resource: ['transcription'], operation: ['submit', 'upload', 'quickTranscription'] } },
 			},
 			{
 				displayName: 'Transcription Parameters (JSON)',
 				name: 'transcriptionParameters',
 				type: 'json',
 				default: '{}',
 				description: 'WhisperX parameters as JSON object',
 				displayOptions: { show: { resource: ['transcription'], operation: ['startTranscription', 'quickTranscription'] } },
 				routing: { send: { type: 'body', property: 'parameters' } },
 			},
 			{
 				displayName: 'Profile Name',
 				name: 'profileName',
 				type: 'string',
 				default: '',
 				description: 'Profile name to use for transcription',
 				displayOptions: { show: { resource: ['transcription'], operation: ['quickTranscription'] } },
 			},
 			{
 				displayName: 'Title',
 				name: 'title',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'New title for the transcription',
 				displayOptions: { show: { resource: ['transcription'], operation: ['updateTitle'] } },
 				routing: { send: { type: 'body', property: 'title' } },
 			},
 			{
 				displayName: 'Page',
 				name: 'page',
 				type: 'number',
 				default: 1,
 				description: 'Page number',
 				displayOptions: { show: { resource: ['transcription'], operation: ['list'] } },
 				routing: { request: { qs: { page: '={{$value}}' } } },
 			},
	 			{
	 				displayName: 'Limit',
	 				name: 'limit',
	 				type: 'number',
	 				default: 50,
	 				description: 'Max number of results to return',
	 				displayOptions: { show: { resource: ['transcription'], operation: ['list'] } },
	 				typeOptions: { minValue: 1, maxValue: 100 },
	 				routing: { request: { qs: { limit: '={{$value}}' } } },
	 			},
 			{
 				displayName: 'Status',
 				name: 'status',
 				type: 'options',
	 				options: [
	 					{ name: 'Completed', value: 'completed' },
	 					{ name: 'Failed', value: 'failed' },
	 					{ name: 'Pending', value: 'pending' },
	 					{ name: 'Processing', value: 'processing' },
	 					{ name: 'Uploaded', value: 'uploaded' },
	 				],
	 				default: 'uploaded',
 				description: 'Filter by status',
 				displayOptions: { show: { resource: ['transcription'], operation: ['list'] } },
 				routing: { request: { qs: { status: '={{$value}}' } } },
 			},
 			{
 				displayName: 'Search',
 				name: 'q',
 				type: 'string',
 				default: '',
 				description: 'Search in title and audio filename',
 				displayOptions: { show: { resource: ['transcription'], operation: ['list'] } },
 				routing: { request: { qs: { q: '={{$value}}' } } },
 			},

 			// Admin operations
 			{
 				displayName: 'Operation',
 				name: 'operation',
 				type: 'options',
 				noDataExpression: true,
 				displayOptions: { show: { resource: ['admin'] } },
	 				options: [
	 					{
	 						name: 'Get Queue Stats',
	 						value: 'getQueueStats',
	 						action: 'Get queue statistics',
	 						description: 'Get current queue statistics',
								routing: { request: { method: 'GET', url: '/api/v1/admin/queue/stats' } },
	 					},
	 				],
 				default: 'getQueueStats',
 			},

 			// API Key operations
 			{
 				displayName: 'Operation',
 				name: 'operation',
 				type: 'options',
 				noDataExpression: true,
 				displayOptions: { show: { resource: ['apiKey'] } },
 				hint: 'API Key operations require JWT (Bearer Token) authentication, not API Key authentication. Please use JWT authentication method.',
	 				options: [
	 					{
	 						name: 'Create',
	 						value: 'create',
	 						action: 'Create API key',
	 						description: 'Create a new API key for external API access',
								routing: { request: { method: 'POST', url: '/api/v1/api-keys' } },
	 					},
	 					{
	 						name: 'Delete',
	 						value: 'delete',
	 						action: 'Delete API key',
	 						description: 'Delete an API key',
								routing: { request: { method: 'DELETE', url: '/api/v1/api-keys/{{$parameter["apiKeyId"]}}' } },
	 					},
	 					{
	 						name: 'List',
	 						value: 'list',
	 						action: 'List API keys',
	 						description: 'Get all API keys for the current user (without exposing the actual keys)',
								routing: { request: { method: 'GET', url: '/api/v1/api-keys' } },
	 					},
	 				],
 				default: 'list',
 			},
 			{
 				displayName: 'API Key ID',
 				name: 'apiKeyId',
 				type: 'number',
 				default: 0,
 				required: true,
 				description: 'ID of the API key',
 				displayOptions: { show: { resource: ['apiKey'], operation: ['delete'] } },
 			},
 			{
 				displayName: 'Name',
 				name: 'apiKeyName',
 				type: 'string',
					typeOptions: { password: true },
 				default: '',
 				required: true,
 				description: 'Name for the API key',
 				displayOptions: { show: { resource: ['apiKey'], operation: ['create'] } },
 				routing: { send: { type: 'body', property: 'name' } },
 			},
 			{
 				displayName: 'Description',
 				name: 'apiKeyDescription',
 				type: 'string',
					typeOptions: { password: true },
 				default: '',
 				description: 'Optional description for the API key',
 				displayOptions: { show: { resource: ['apiKey'], operation: ['create'] } },
 				routing: { send: { type: 'body', property: 'description' } },
 			},

 			// Auth operations
 			{
 				displayName: 'Operation',
 				name: 'operation',
 				type: 'options',
 				noDataExpression: true,
 				displayOptions: { show: { resource: ['auth'] } },
 				hint: 'Change Password and Change Username operations require JWT (Bearer Token) authentication',
	 				options: [
	 					{
	 						name: 'Change Password',
	 						value: 'changePassword',
	 						action: 'Change user password',
	 						description: "Change the current user's password",
								routing: { request: { method: 'POST', url: '/api/v1/auth/change-password' } },
	 					},
	 					{
	 						name: 'Change Username',
	 						value: 'changeUsername',
	 						action: 'Change username',
	 						description: "Change the current user's username",
								routing: { request: { method: 'POST', url: '/api/v1/auth/change-username' } },
	 					},
	 					{
	 						name: 'Login',
	 						value: 'login',
	 						action: 'Login',
	 						description: 'Authenticate user and return JWT token',
								routing: { request: { method: 'POST', url: '/api/v1/auth/login' } },
	 					},
	 					{
	 						name: 'Logout',
	 						value: 'logout',
	 						action: 'Logout user',
	 						description: 'Logout user and invalidate token (client-side action)',
								routing: { request: { method: 'POST', url: '/api/v1/auth/logout' } },
	 					},
	 					{
	 						name: 'Register',
	 						value: 'register',
	 						action: 'Register initial admin user',
	 						description: 'Register the initial admin user (only allowed when no users exist)',
								routing: { request: { method: 'POST', url: '/api/v1/auth/register' } },
	 					},
	 					{
	 						name: 'Registration Status',
	 						value: 'registrationStatus',
	 						action: 'Check registration status',
	 						description: 'Check if the application requires initial user registration',
								routing: { request: { method: 'GET', url: '/api/v1/auth/registration-status' } },
	 					},
	 				],
 				default: 'registrationStatus',
 			},
 			{
 				displayName: 'Username',
 				name: 'username',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Username for authentication',
 				displayOptions: { show: { resource: ['auth'], operation: ['login', 'register'] } },
 				routing: { send: { type: 'body', property: 'username' } },
 			},
 			{
 				displayName: 'Password',
 				name: 'password',
 				type: 'string',
 				typeOptions: { password: true },
 				default: '',
 				required: true,
 				description: 'Password for authentication',
 				displayOptions: { show: { resource: ['auth'], operation: ['login', 'register', 'changeUsername'] } },
 				routing: { send: { type: 'body', property: 'password' } },
 			},
 			{
 				displayName: 'Confirm Password',
 				name: 'confirmPassword',
 				type: 'string',
 				typeOptions: { password: true },
 				default: '',
 				required: true,

 				displayOptions: { show: { resource: ['auth'], operation: ['register', 'changePassword'] } },
 				routing: { send: { type: 'body', property: 'confirmPassword' } },
 			},
 			{
 				displayName: 'Current Password',
 				name: 'currentPassword',
 				type: 'string',
 				typeOptions: { password: true },
 				default: '',
 				required: true,

 				displayOptions: { show: { resource: ['auth'], operation: ['changePassword'] } },
 				routing: { send: { type: 'body', property: 'currentPassword' } },
 			},
 			{
 				displayName: 'New Password',
 				name: 'newPassword',
 				type: 'string',
 				typeOptions: { password: true },
 				default: '',
 				required: true,
 				description: 'New password (minimum 6 characters)',
 				displayOptions: { show: { resource: ['auth'], operation: ['changePassword'] } },
 				routing: { send: { type: 'body', property: 'newPassword' } },
 			},
 			{
 				displayName: 'New Username',
 				name: 'newUsername',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'New username (3-50 characters)',
 				displayOptions: { show: { resource: ['auth'], operation: ['changeUsername'] } },
 				routing: { send: { type: 'body', property: 'newUsername' } },
 			},

 			// Health operations
 			{
 				displayName: 'Operation',
 				name: 'operation',
 				type: 'options',
 				noDataExpression: true,
 				displayOptions: { show: { resource: ['health'] } },
	 				options: [
	 					{
	 						name: 'Health Check',
	 						value: 'healthCheck',
	 						action: 'Health check',
	 						description: 'Check if the API is healthy',
								routing: { request: { method: 'GET', url: '/health' } },
	 					},
	 				],
 				default: 'healthCheck',
 			},

 			// LLM operations
 			{
 				displayName: 'Operation',
 				name: 'operation',
 				type: 'options',
 				noDataExpression: true,
 				displayOptions: { show: { resource: ['llm'] } },
 				hint: 'LLM configuration operations require JWT (Bearer Token) authentication',
	 				options: [
	 					{
	 						name: 'Get Config',
	 						value: 'getConfig',
	 						action: 'Get LLM configuration',
	 						description: 'Get the current active LLM configuration',
								routing: { request: { method: 'GET', url: '/api/v1/llm/config' } },
	 					},
	 					{
	 						name: 'Set Config',
	 						value: 'setConfig',
	 						action: 'Create or update LLM configuration',
	 						description: 'Create or update LLM configuration settings',
								routing: { request: { method: 'POST', url: '/api/v1/llm/config' } },
	 					},
	 				],
 				default: 'getConfig',
 			},
 			{
 				displayName: 'Provider',
 				name: 'llmProvider',
 				type: 'options',
 				options: [
 					{ name: 'Ollama', value: 'ollama' },
 					{ name: 'OpenAI', value: 'openai' },
 				],
 				default: 'openai',
 				required: true,
 				description: 'LLM provider',
 				displayOptions: { show: { resource: ['llm'], operation: ['setConfig'] } },
 				routing: { send: { type: 'body', property: 'provider' } },
 			},
 			{
 				displayName: 'API Key',
 				name: 'llmApiKey',
 				type: 'string',
 				typeOptions: { password: true },
 				default: '',
 				description: 'API key for the LLM provider',
 				displayOptions: { show: { resource: ['llm'], operation: ['setConfig'] } },
 				routing: { send: { type: 'body', property: 'api_key' } },
 			},
 			{
 				displayName: 'Base URL',
 				name: 'llmBaseUrl',
 				type: 'string',
 				default: '',
 				description: 'Base URL for the LLM provider (optional)',
 				displayOptions: { show: { resource: ['llm'], operation: ['setConfig'] } },
 				routing: { send: { type: 'body', property: 'base_url' } },
 			},
 			{
 				displayName: 'Is Active',
 				name: 'llmIsActive',
 				type: 'boolean',
 				default: true,
 				description: 'Whether this configuration is active',
 				displayOptions: { show: { resource: ['llm'], operation: ['setConfig'] } },
 				routing: { send: { type: 'body', property: 'is_active' } },
 			},

 			// Profile operations
 			{
 				displayName: 'Operation',
 				name: 'operation',
 				type: 'options',
 				noDataExpression: true,
 				displayOptions: { show: { resource: ['profile'] } },
	 				options: [
	 					{
	 						name: 'Create',
	 						value: 'create',
	 						action: 'Create transcription profile',
	 						description: 'Create a new transcription profile',
								routing: { request: { method: 'POST', url: '/api/v1/profiles' } },
	 					},
	 					{
	 						name: 'Delete',
	 						value: 'delete',
	 						action: 'Delete transcription profile',
	 						description: 'Delete a transcription profile',
								routing: { request: { method: 'DELETE', url: '/api/v1/profiles/{{$parameter["profileId"]}}' } },
	 					},
	 					{
	 						name: 'Get',
	 						value: 'get',
	 						action: 'Get transcription profile',
	 						description: 'Get a transcription profile by ID',
								routing: { request: { method: 'GET', url: '/api/v1/profiles/{{$parameter["profileId"]}}' } },
	 					},
	 					{
	 						name: 'List',
	 						value: 'list',
	 						action: 'List transcription profiles',
	 						description: 'Get list of all transcription profiles',
								routing: { request: { method: 'GET', url: '/api/v1/profiles' } },
	 					},
	 					{
	 						name: 'Set Default',
	 						value: 'setDefault',
	 						action: 'Set default transcription profile',
	 						description: 'Mark the specified profile as the default profile',
								routing: { request: { method: 'POST', url: '/api/v1/profiles/{{$parameter["profileId"]}}/set-default' } },
	 					},
	 					{
	 						name: 'Update',
	 						value: 'update',
	 						action: 'Update transcription profile',
	 						description: 'Update a transcription profile',
								routing: { request: { method: 'PUT', url: '/api/v1/profiles/{{$parameter["profileId"]}}' } },
	 					},
	 				],
 				default: 'list',
 			},
 			{
 				displayName: 'Profile ID',
 				name: 'profileId',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'ID of the transcription profile',
 				displayOptions: { show: { resource: ['profile'], operation: ['get', 'update', 'delete', 'setDefault'] } },
 			},
 			{
 				displayName: 'Name',
 				name: 'profileName',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Profile name',
 				displayOptions: { show: { resource: ['profile'], operation: ['create', 'update'] } },
 				routing: { send: { type: 'body', property: 'name' } },
 			},
 			{
 				displayName: 'Description',
 				name: 'profileDescription',
 				type: 'string',
 				default: '',
 				description: 'Profile description',
 				displayOptions: { show: { resource: ['profile'], operation: ['create', 'update'] } },
 				routing: { send: { type: 'body', property: 'description' } },
 			},
 			{
 				displayName: 'Parameters (JSON)',
 				name: 'profileParameters',
 				type: 'json',
 				default: '{}',
 				description: 'WhisperX parameters as JSON object',
 				displayOptions: { show: { resource: ['profile'], operation: ['create', 'update'] } },
 				routing: { send: { type: 'body', property: 'parameters' } },
 			},

 			// Notes operations
 			{
 				displayName: 'Operation',
 				name: 'operation',
 				type: 'options',
 				noDataExpression: true,
	 				displayOptions: { show: { resource: ['note'] } },
 				options: [
						{ name: 'Create', value: 'create', action: 'Create note', description: 'Create a note for a transcription', routing: { request: { method: 'POST', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}/notes' } } },
						{ name: 'Delete', value: 'delete', action: 'Delete note', description: 'Delete a note by ID', routing: { request: { method: 'DELETE', url: '/api/v1/notes/{{$parameter["noteId"]}}' } } },
						{ name: 'Get', value: 'get', action: 'Get note', description: 'Get a note by ID', routing: { request: { method: 'GET', url: '/api/v1/notes/{{$parameter["noteId"]}}' } } },
						{ name: 'List For Transcription', value: 'listForTranscription', action: 'List notes', description: 'List notes for a transcription', routing: { request: { method: 'GET', url: '/api/v1/transcription/{{$parameter["transcriptionId"]}}/notes' } } },
						{ name: 'Update', value: 'update', action: 'Update a note by ID', routing: { request: { method: 'PUT', url: '/api/v1/notes/{{$parameter["noteId"]}}' } } },
 				],
 				default: 'listForTranscription',
 			},
 			{
 				displayName: 'Transcription ID',
 				name: 'transcriptionId',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'ID of the transcription record',
	 			displayOptions: { show: { resource: ['note'], operation: ['listForTranscription','create'] } },
 			},
 			{
 				displayName: 'Note ID',
 				name: 'noteId',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'ID of the note',
	 			displayOptions: { show: { resource: ['note'], operation: ['get','update','delete'] } },
 			},
 			{
 				displayName: 'Content',
 				name: 'content',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'The note content (markdown/plain)',
	 			displayOptions: { show: { resource: ['note'], operation: ['create','update'] } },
 				routing: { send: { type: 'body', property: 'content' } },
 			},
 			{
 				displayName: 'Quote',
 				name: 'quote',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'The exact quoted text chosen by the user',
	 			displayOptions: { show: { resource: ['note'], operation: ['create'] } },
 				routing: { send: { type: 'body', property: 'quote' } },
 			},
 			{
	 			displayName: 'Start Time (Seconds)',
 				name: 'start_time',
 				type: 'number',
 				default: 0,
 				description: 'Start time bound for the selection',
	 			displayOptions: { show: { resource: ['note'], operation: ['create'] } },
 				routing: { send: { type: 'body', property: 'start_time' } },
 			},
 			{
	 			displayName: 'End Time (Seconds)',
 				name: 'end_time',
 				type: 'number',
 				default: 0,
 				description: 'End time bound for the selection',
	 			displayOptions: { show: { resource: ['note'], operation: ['create'] } },
 				routing: { send: { type: 'body', property: 'end_time' } },
 			},
 			{
 				displayName: 'Start Word Index',
 				name: 'start_word_index',
 				type: 'number',
 				default: 0,
 				description: 'Indexed selection into transcript by word positions (start)',
	 			displayOptions: { show: { resource: ['note'], operation: ['create'] } },
 				routing: { send: { type: 'body', property: 'start_word_index' } },
 			},
 			{
 				displayName: 'End Word Index',
 				name: 'end_word_index',
 				type: 'number',
 				default: 0,
 				description: 'Indexed selection into transcript by word positions (end)',
	 			displayOptions: { show: { resource: ['note'], operation: ['create'] } },
 				routing: { send: { type: 'body', property: 'end_word_index' } },
 			},

 			// Chat operations
 			{
 				displayName: 'Operation',
 				name: 'operation',
 				type: 'options',
 				noDataExpression: true,
 				displayOptions: { show: { resource: ['chat'] } },
	 				options: [
						{ name: 'Auto-Generate Title', value: 'autoGenerateTitle', action: 'Auto generate chat session title', description: 'Uses the configured LLM to summarize the first exchange into a concise title', routing: { request: { method: 'POST', url: '/api/v1/chat/sessions/{{$parameter["sessionId"]}}/title/auto' } } },
						{ name: 'Create Session', value: 'createSession', action: 'Create chat session', description: 'Create a new chat session for a transcription', routing: { request: { method: 'POST', url: '/api/v1/chat/sessions' } } },
						{ name: 'Delete Session', value: 'deleteSession', action: 'Delete chat session', description: 'Delete a chat session and all its messages', routing: { request: { method: 'DELETE', url: '/api/v1/chat/sessions/{{$parameter["sessionId"]}}' } } },
						{ name: 'Get Models', value: 'getModels', action: 'Get available chat models', description: 'Get list of available chat models', routing: { request: { method: 'GET', url: '/api/v1/chat/models' } } },
						{ name: 'Get Session', value: 'getSession', action: 'Get chat session', description: 'Get a chat session with its messages', routing: { request: { method: 'GET', url: '/api/v1/chat/sessions/{{$parameter["sessionId"]}}' } } },
						{ name: 'List Sessions For Transcription', value: 'listSessionsForTranscription', action: 'List chat sessions for transcription', description: 'Get all chat sessions for a specific transcription', routing: { request: { method: 'GET', url: '/api/v1/chat/transcriptions/{{$parameter["transcriptionId"]}}/sessions' } } },
						{ name: 'Send Message', value: 'sendMessage', action: 'Send message to session', description: 'Send a message to a chat session and get response', routing: { request: { method: 'POST', url: '/api/v1/chat/sessions/{{$parameter["sessionId"]}}/messages' } } },
						{ name: 'Update Session Title', value: 'updateSessionTitle', action: 'Update chat session title', description: 'Update the title of a chat session', routing: { request: { method: 'PUT', url: '/api/v1/chat/sessions/{{$parameter["sessionId"]}}/title' } } },
	 				],
 				default: 'getModels',
 			},
 			{
 				displayName: 'Session ID',
 				name: 'sessionId',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'ID of the chat session',
 				displayOptions: { show: { resource: ['chat'], operation: ['getSession','sendMessage','deleteSession','updateSessionTitle','autoGenerateTitle'] } },
 			},
 			{
 				displayName: 'Session Title',
 				name: 'sessionTitle',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'New title for the chat session',
 				displayOptions: { show: { resource: ['chat'], operation: ['updateSessionTitle'] } },
 				routing: { send: { type: 'body', property: 'title' } },
 			},
 			{
 				displayName: 'Model',
 				name: 'model',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Model name (provider must be configured in Scriberr)',
 				displayOptions: { show: { resource: ['chat'], operation: ['createSession'] } },
 				routing: { send: { type: 'body', property: 'model' } },
 			},
 			{
 				displayName: 'Transcription ID',
 				name: 'transcriptionId',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Transcription to attach the chat session to',
 				displayOptions: { show: { resource: ['chat'], operation: ['createSession','listSessionsForTranscription'] } },
 				routing: { send: { type: 'body', property: 'transcription_id' } },
 			},
 			{
 				displayName: 'Message',
 				name: 'content',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Message content to send',
 				displayOptions: { show: { resource: ['chat'], operation: ['sendMessage'] } },
 				routing: { send: { type: 'body', property: 'content' } },
 			},

 			// Summaries operations
 			{
 				displayName: 'Operation',
 				name: 'operation',
 				type: 'options',
 				noDataExpression: true,
	 			displayOptions: { show: { resource: ['summary'] } },
	 				options: [
						{ name: 'Create Template', value: 'createTemplate', action: 'Create summary template', description: 'Create a new summarization template', routing: { request: { method: 'POST', url: '/api/v1/summaries' } } },
						{ name: 'Delete Template', value: 'deleteTemplate', action: 'Delete summary template', description: 'Delete a summarization template by ID', routing: { request: { method: 'DELETE', url: '/api/v1/summaries/{{$parameter["templateId"]}}' } } },
						{ name: 'Get Settings', value: 'getSettings', action: 'Get summary settings', description: 'Get global summarization settings', routing: { request: { method: 'GET', url: '/api/v1/summaries/settings' } } },
						{ name: 'Get Template', value: 'getTemplate', action: 'Get summary template', description: 'Get a summarization template by ID', routing: { request: { method: 'GET', url: '/api/v1/summaries/{{$parameter["templateId"]}}' } } },
						{ name: 'List Templates', value: 'listTemplates', action: 'List summary templates', description: 'Get all summarization templates', routing: { request: { method: 'GET', url: '/api/v1/summaries' } } },
						{ name: 'Save Settings', value: 'saveSettings', action: 'Save summary settings', description: 'Create or update global summarization settings', routing: { request: { method: 'POST', url: '/api/v1/summaries/settings' } } },
						{ name: 'Summarize', value: 'summarize', action: 'Summarize content', description: 'Stream an LLM-generated summary for provided content', routing: { request: { method: 'POST', url: '/api/v1/summarize', headers: { Accept: 'text/event-stream' } } } },
						{ name: 'Update Template', value: 'updateTemplate', action: 'Update summary template', description: 'Update a summarization template by ID', routing: { request: { method: 'PUT', url: '/api/v1/summaries/{{$parameter["templateId"]}}' } } },
	 				],
 				default: 'listTemplates',
 			},
 			{
 				displayName: 'Template ID',
 				name: 'templateId',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'ID of the summary template',
	 			displayOptions: { show: { resource: ['summary'], operation: ['getTemplate','updateTemplate','deleteTemplate'] } },
 			},
 			{
 				displayName: 'Default Model',
 				name: 'defaultModel',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Default model for summarization',
 				displayOptions: { show: { resource: ['summary'], operation: ['saveSettings'] } },
 				routing: { send: { type: 'body', property: 'default_model' } },
 			},
 			{
 				displayName: 'Name',
 				name: 'name',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Template name',
	 			displayOptions: { show: { resource: ['summary'], operation: ['createTemplate','updateTemplate'] } },
 				routing: { send: { type: 'body', property: 'name' } },
 			},
 			{
 				displayName: 'Model',
 				name: 'summaryModel',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Model to use for this template',
	 			displayOptions: { show: { resource: ['summary'], operation: ['createTemplate','updateTemplate'] } },
 				routing: { send: { type: 'body', property: 'model' } },
 			},
 			{
 				displayName: 'Prompt',
 				name: 'prompt',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Prompt used by the template',
 				typeOptions: { rows: 4 },
	 			displayOptions: { show: { resource: ['summary'], operation: ['createTemplate','updateTemplate'] } },
 				routing: { send: { type: 'body', property: 'prompt' } },
 			},
 			{
 				displayName: 'Description',
 				name: 'description',
 				type: 'string',
 				default: '',
 				description: 'Optional description for the template',
				displayOptions: { show: { resource: ['summary'], operation: ['createTemplate','updateTemplate'] } },
 				routing: { send: { type: 'body', property: 'description' } },
 			},
 			{
 				displayName: 'Transcription ID',
 				name: 'sumTranscriptionId',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Transcription ID to summarize',
	 			displayOptions: { show: { resource: ['summary'], operation: ['summarize'] } },
 				routing: { send: { type: 'body', property: 'transcription_id' } },
 			},
 			{
 				displayName: 'Model',
 				name: 'sumModel',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Model to use for summarization',
	 			displayOptions: { show: { resource: ['summary'], operation: ['summarize'] } },
 				routing: { send: { type: 'body', property: 'model' } },
 			},
 			{
 				displayName: 'Content',
 				name: 'sumContent',
 				type: 'string',
 				default: '',
 				required: true,
 				description: 'Content to summarize',
 				typeOptions: { rows: 4 },
	 			displayOptions: { show: { resource: ['summary'], operation: ['summarize'] } },
 				routing: { send: { type: 'body', property: 'content' } },
 			},
 			{
 				displayName: 'Template ID',
 				name: 'sumTemplateId',
 				type: 'string',
 				default: '',
 				description: 'Optional template ID to use for summarization',
				displayOptions: { show: { resource: ['summary'], operation: ['summarize'] } },
 				routing: { send: { type: 'body', property: 'template_id' } },
 			},
 		],
 	};
}
