name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'  # Only trigger when version changes
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write  # For creating releases and pushing tags
  id-token: write  # For npm provenance

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for changelog
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm run release --ci ${{ github.event.inputs.version && format('--increment={0}', github.event.inputs.version) || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}